3dcenter_loss_coef: 10
angle_loss_coef: 1
aux_loss: true
backbone: resnet34
bbox_loss_coef: 5
box_noise_scale: 0.4
cbr_3d_loss_coef: 0
cls_loss_coef: 2
dec_layers: 3
dec_n_points: 4
deform_attn_torch: false
depth_guidance: false
depth_loss_coef: 1
depth_map_loss_coef: 1
depth_max: 60.0
depth_min: 0.001
depth_predictor2loss: true
device: cuda
dilation: false
dim_feedforward: 256
dim_loss_coef: 1
dropout: 0.1
enc_layers: 3
enc_n_points: 4
focal_alpha: 0.25
giou_loss_coef: 2
group_num: 11
hidden_dim: 256
init_box: false
label_noise_scale: 0.2
masks: false
mode: LID
nheads: 8
num_classes: 3
num_depth_bins: 80
num_feature_levels: 4
num_patterns: 0
num_queries: 50
position_embedding: sine
return_intermediate_dec: true
rtdetr_visual_encoder: false
scalar: 5
set_cost_3dcenter: 10
set_cost_bbox: 5
set_cost_class: 2
set_cost_giou: 2
train_backbone: true
two_stage: false
two_stage_dino: false
use_dab: false
use_dn: false
with_box_refine: true
